GridLayout:
    id: grid_layout
    padding: 10
    spacing: 10
    cols:3
    Button:
        text: "1"
        size_hint_x: None
        width: 30
    Button:
        text: "2"
    Button:
        text: "3"
    Button:
        text: "4"
        size_hint_x: None
        width: 30
    Button:
        text: "5"
    Button:
        text: "6"
    Button:
        text: "7"
        size_hint_x: None
        width: 30
    Button:
        text: "8"
    Button:
        text: "9"
