# Compiled Coconut: -----------------------------------------------------------

def factorial_variant_B(n):  #1 (line in Coconut source)
    _coconut_case_match_to_0 = n  #2 (line in Coconut source)
    _coconut_case_match_check_0 = False  #2 (line in Coconut source)
    if _coconut_case_match_to_0 == 0:  #2 (line in Coconut source)
        _coconut_case_match_check_0 = True  #2 (line in Coconut source)
    if _coconut_case_match_check_0:  #2 (line in Coconut source)
        return 1  #4 (line in Coconut source)
    if not _coconut_case_match_check_0:  #5 (line in Coconut source)
        if _coconut_case_match_to_0 == 1:  #5 (line in Coconut source)
            _coconut_case_match_check_0 = True  #5 (line in Coconut source)
        if _coconut_case_match_check_0:  #5 (line in Coconut source)
            return 1  #6 (line in Coconut source)
    if not _coconut_case_match_check_0:  #7 (line in Coconut source)
        _coconut_match_set_name_x = _coconut_sentinel  #7 (line in Coconut source)
        _coconut_match_set_name_x = _coconut_case_match_to_0  #7 (line in Coconut source)
        _coconut_case_match_check_0 = True  #7 (line in Coconut source)
        if _coconut_case_match_check_0:  #7 (line in Coconut source)
            if _coconut_match_set_name_x is not _coconut_sentinel:  #7 (line in Coconut source)
                x = _coconut_match_set_name_x  #7 (line in Coconut source)
        if _coconut_case_match_check_0 and not (x > 1):  #7 (line in Coconut source)
            _coconut_case_match_check_0 = False  #7 (line in Coconut source)
        if _coconut_case_match_check_0:  #7 (line in Coconut source)
            return x * factorial_variant_B(x - 1)  #8 (line in Coconut source)
    if not _coconut_case_match_check_0:  #9 (line in Coconut source)
        raise TypeError("expecting integer >= 0")  #10 (line in Coconut source)


print(factorial_variant_B("foo"))  #12 (line in Coconut source)
