# Compiled Coconut: -----------------------------------------------------------

def complex_number(value):  #1 (line in Coconut source)
    """Test, o jakou variantu komplexního čísla se jedná."""  #2 (line in Coconut source)
    _coconut_case_match_to_0 = value  #3 (line in Coconut source)
    _coconut_case_match_check_0 = False  #3 (line in Coconut source)
    if (_coconut.isinstance(_coconut_case_match_to_0, _coconut.abc.Sequence)) and (_coconut.len(_coconut_case_match_to_0) == 2) and (_coconut_case_match_to_0[0] == 0) and (_coconut_case_match_to_0[1] == 0):  #3 (line in Coconut source)
        _coconut_case_match_check_0 = True  #3 (line in Coconut source)
    if _coconut_case_match_check_0:  #3 (line in Coconut source)
        print("Zero")  #5 (line in Coconut source)
    if not _coconut_case_match_check_0:  #6 (line in Coconut source)
        _coconut_match_set_name_real = _coconut_sentinel  #6 (line in Coconut source)
        if (_coconut.isinstance(_coconut_case_match_to_0, _coconut.abc.Sequence)) and (_coconut.len(_coconut_case_match_to_0) == 2) and (_coconut_case_match_to_0[1] == 0):  #6 (line in Coconut source)
            _coconut_match_set_name_real = _coconut_case_match_to_0[0]  #6 (line in Coconut source)
            _coconut_case_match_check_0 = True  #6 (line in Coconut source)
        if _coconut_case_match_check_0:  #6 (line in Coconut source)
            if _coconut_match_set_name_real is not _coconut_sentinel:  #6 (line in Coconut source)
                real = _coconut_match_set_name_real  #6 (line in Coconut source)
        if _coconut_case_match_check_0:  #6 (line in Coconut source)
            print("Real number {_coconut_format_0}".format(_coconut_format_0=(real)))  #7 (line in Coconut source)
    if not _coconut_case_match_check_0:  #8 (line in Coconut source)
        _coconut_match_set_name_imag = _coconut_sentinel  #8 (line in Coconut source)
        if (_coconut.isinstance(_coconut_case_match_to_0, _coconut.abc.Sequence)) and (_coconut.len(_coconut_case_match_to_0) == 2) and (_coconut_case_match_to_0[0] == 0):  #8 (line in Coconut source)
            _coconut_match_set_name_imag = _coconut_case_match_to_0[1]  #8 (line in Coconut source)
            _coconut_case_match_check_0 = True  #8 (line in Coconut source)
        if _coconut_case_match_check_0:  #8 (line in Coconut source)
            if _coconut_match_set_name_imag is not _coconut_sentinel:  #8 (line in Coconut source)
                imag = _coconut_match_set_name_imag  #8 (line in Coconut source)
        if _coconut_case_match_check_0:  #8 (line in Coconut source)
            print("Imaginary number {_coconut_format_0}".format(_coconut_format_0=(imag)))  #9 (line in Coconut source)
    if not _coconut_case_match_check_0:  #10 (line in Coconut source)
        _coconut_match_set_name_real = _coconut_sentinel  #10 (line in Coconut source)
        _coconut_match_set_name_imag = _coconut_sentinel  #10 (line in Coconut source)
        if (_coconut.isinstance(_coconut_case_match_to_0, _coconut.abc.Sequence)) and (_coconut.len(_coconut_case_match_to_0) == 2):  #10 (line in Coconut source)
            _coconut_match_set_name_real = _coconut_case_match_to_0[0]  #10 (line in Coconut source)
            _coconut_match_set_name_imag = _coconut_case_match_to_0[1]  #10 (line in Coconut source)
            _coconut_case_match_check_0 = True  #10 (line in Coconut source)
        if _coconut_case_match_check_0:  #10 (line in Coconut source)
            if _coconut_match_set_name_real is not _coconut_sentinel:  #10 (line in Coconut source)
                real = _coconut_match_set_name_real  #10 (line in Coconut source)
            if _coconut_match_set_name_imag is not _coconut_sentinel:  #10 (line in Coconut source)
                imag = _coconut_match_set_name_imag  #10 (line in Coconut source)
        if _coconut_case_match_check_0:  #10 (line in Coconut source)
            print("Complex number {_coconut_format_0}+i{_coconut_format_1}".format(_coconut_format_0=(real), _coconut_format_1=(imag)))  #11 (line in Coconut source)
    if not _coconut_case_match_check_0:  #12 (line in Coconut source)
        _coconut_case_match_check_0 = True  #12 (line in Coconut source)
        if _coconut_case_match_check_0:  #12 (line in Coconut source)
            raise ValueError("Not a complex number")  #13 (line in Coconut source)



complex_number((0, 0))  #16 (line in Coconut source)
complex_number((1, 0))  #17 (line in Coconut source)
complex_number((0, 1))  #18 (line in Coconut source)
complex_number((1, 1))  #19 (line in Coconut source)
complex_number("foo")  #20 (line in Coconut source)
