# Compiled Coconut: -----------------------------------------------------------

def pair(p):  #1 (line in Coconut source)
    _coconut_case_match_to_0 = p  #2 (line in Coconut source)
    _coconut_case_match_check_0 = False  #2 (line in Coconut source)
    _coconut_match_set_name_x = _coconut_sentinel  #2 (line in Coconut source)
    if (_coconut.isinstance(_coconut_case_match_to_0, _coconut.abc.Sequence)) and (_coconut.len(_coconut_case_match_to_0) == 2):  #2 (line in Coconut source)
        _coconut_match_set_name_x = _coconut_case_match_to_0[0]  #2 (line in Coconut source)
        if _coconut_match_set_name_x == _coconut_case_match_to_0[1]:  #2 (line in Coconut source)
            _coconut_case_match_check_0 = True  #2 (line in Coconut source)
    if _coconut_case_match_check_0:  #2 (line in Coconut source)
        if _coconut_match_set_name_x is not _coconut_sentinel:  #2 (line in Coconut source)
            x = _coconut_match_set_name_x  #2 (line in Coconut source)
    if _coconut_case_match_check_0:  #2 (line in Coconut source)
        return "same values!"  #4 (line in Coconut source)
    if not _coconut_case_match_check_0:  #5 (line in Coconut source)
        _coconut_match_set_name_x = _coconut_sentinel  #5 (line in Coconut source)
        _coconut_match_set_name_y = _coconut_sentinel  #5 (line in Coconut source)
        if (_coconut.isinstance(_coconut_case_match_to_0, _coconut.abc.Sequence)) and (_coconut.len(_coconut_case_match_to_0) == 2):  #5 (line in Coconut source)
            _coconut_match_set_name_x = _coconut_case_match_to_0[0]  #5 (line in Coconut source)
            _coconut_match_set_name_y = _coconut_case_match_to_0[1]  #5 (line in Coconut source)
            _coconut_case_match_check_0 = True  #5 (line in Coconut source)
        if _coconut_case_match_check_0:  #5 (line in Coconut source)
            if _coconut_match_set_name_x is not _coconut_sentinel:  #5 (line in Coconut source)
                x = _coconut_match_set_name_x  #5 (line in Coconut source)
            if _coconut_match_set_name_y is not _coconut_sentinel:  #5 (line in Coconut source)
                y = _coconut_match_set_name_y  #5 (line in Coconut source)
        if _coconut_case_match_check_0 and not (x > y):  #5 (line in Coconut source)
            _coconut_case_match_check_0 = False  #5 (line in Coconut source)
        if _coconut_case_match_check_0:  #5 (line in Coconut source)
            return "1st value is greater"  #6 (line in Coconut source)
    if not _coconut_case_match_check_0:  #7 (line in Coconut source)
        _coconut_match_set_name_x = _coconut_sentinel  #7 (line in Coconut source)
        _coconut_match_set_name_y = _coconut_sentinel  #7 (line in Coconut source)
        if (_coconut.isinstance(_coconut_case_match_to_0, _coconut.abc.Sequence)) and (_coconut.len(_coconut_case_match_to_0) == 2):  #7 (line in Coconut source)
            _coconut_match_set_name_x = _coconut_case_match_to_0[0]  #7 (line in Coconut source)
            _coconut_match_set_name_y = _coconut_case_match_to_0[1]  #7 (line in Coconut source)
            _coconut_case_match_check_0 = True  #7 (line in Coconut source)
        if _coconut_case_match_check_0:  #7 (line in Coconut source)
            if _coconut_match_set_name_x is not _coconut_sentinel:  #7 (line in Coconut source)
                x = _coconut_match_set_name_x  #7 (line in Coconut source)
            if _coconut_match_set_name_y is not _coconut_sentinel:  #7 (line in Coconut source)
                y = _coconut_match_set_name_y  #7 (line in Coconut source)
        if _coconut_case_match_check_0:  #7 (line in Coconut source)
            return "2nd value is greater"  #8 (line in Coconut source)
    if not _coconut_case_match_check_0:  #9 (line in Coconut source)
        return "other"  #10 (line in Coconut source)



(print)(pair([1, 1]))  #13 (line in Coconut source)
(print)(pair([1, 2]))  #14 (line in Coconut source)
(print)(pair([2, 1]))  #15 (line in Coconut source)
