# Compiled Coconut: -----------------------------------------------------------

def login(value):  #1 (line in Coconut source)
    _coconut_case_match_to_0 = value  #2 (line in Coconut source)
    _coconut_case_match_check_0 = False  #2 (line in Coconut source)
    _coconut_match_set_name_x = _coconut_sentinel  #2 (line in Coconut source)
    _coconut_match_set_name_y = _coconut_sentinel  #2 (line in Coconut source)
    if _coconut.isinstance(_coconut_case_match_to_0, _coconut.abc.Mapping):  #2 (line in Coconut source)
        _coconut_match_temp_0 = _coconut_case_match_to_0.get("name", _coconut_sentinel)  #2 (line in Coconut source)
        _coconut_match_temp_1 = _coconut_case_match_to_0.get("surname", _coconut_sentinel)  #2 (line in Coconut source)
        if (_coconut_match_temp_0 is not _coconut_sentinel) and (_coconut_match_temp_1 is not _coconut_sentinel):  #2 (line in Coconut source)
            _coconut_match_set_name_x = _coconut_match_temp_0  #2 (line in Coconut source)
            _coconut_match_set_name_y = _coconut_match_temp_1  #2 (line in Coconut source)
            _coconut_case_match_check_0 = True  #2 (line in Coconut source)
    if _coconut_case_match_check_0:  #2 (line in Coconut source)
        if _coconut_match_set_name_x is not _coconut_sentinel:  #2 (line in Coconut source)
            x = _coconut_match_set_name_x  #2 (line in Coconut source)
        if _coconut_match_set_name_y is not _coconut_sentinel:  #2 (line in Coconut source)
            y = _coconut_match_set_name_y  #2 (line in Coconut source)
    if _coconut_case_match_check_0:  #2 (line in Coconut source)
        print("User identified by name {_coconut_format_0} and surname {_coconut_format_1}".format(_coconut_format_0=(x), _coconut_format_1=(y)))  #4 (line in Coconut source)
    if not _coconut_case_match_check_0:  #5 (line in Coconut source)
        _coconut_match_set_name_x = _coconut_sentinel  #5 (line in Coconut source)
        if _coconut.isinstance(_coconut_case_match_to_0, _coconut.abc.Mapping):  #5 (line in Coconut source)
            _coconut_match_temp_2 = _coconut_case_match_to_0.get("id", _coconut_sentinel)  #5 (line in Coconut source)
            if _coconut_match_temp_2 is not _coconut_sentinel:  #5 (line in Coconut source)
                _coconut_match_set_name_x = _coconut_match_temp_2  #5 (line in Coconut source)
                _coconut_case_match_check_0 = True  #5 (line in Coconut source)
        if _coconut_case_match_check_0:  #5 (line in Coconut source)
            if _coconut_match_set_name_x is not _coconut_sentinel:  #5 (line in Coconut source)
                x = _coconut_match_set_name_x  #5 (line in Coconut source)
        if _coconut_case_match_check_0:  #5 (line in Coconut source)
            print("User identified by ID {_coconut_format_0}".format(_coconut_format_0=(x)))  #6 (line in Coconut source)
    if not _coconut_case_match_check_0:  #7 (line in Coconut source)
        print("Unable to identify user")  #8 (line in Coconut source)



login(_coconut.dict((("name", "John"), ("surname", "Joe"))))  #11 (line in Coconut source)
login(_coconut.dict((("id", 42),)))  #12 (line in Coconut source)
login(_coconut.dict((("id", 42), ("name", "John"))))  #13 (line in Coconut source)
login(_coconut.dict((("id", 42), ("name", "John"), ("surname", "Joe"))))  #14 (line in Coconut source)
login(_coconut.dict((("foo", "bar"),)))  #15 (line in Coconut source)
